{
  "services": [
    {
      "type": "web",
      "name": "hostelhub-backend",
      "env": "node",
      "rootDir": "backend",
      "buildCommand": "npm install",
      "startCommand": "node server.js",
      "envVars": [
        {
          "key": "PORT",
          "value": "5000"
        },
        {
          "key": "MONGODB_URI",
          "value": "mongodb+srv://pawanbro584_db_user:oLEh8b6PMjQdFCVA@hostelhub.f7xovve.mongodb.net/?appName=hostelhub"
        },
        {
          "key": "JWT_SECRET",
          "value": "hostelhub"
        },
        {
          "key": "JWT_EXPIRE",
          "value": "30d"
        },
        {
          "key": "SUPABASE_URL",
          "value": "https://ukawqvvcgazrtqvstyyr.supabase.co"
        },
        {
          "key": "SUPABASE_SERVICE_ROLE_KEY",
          "value": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVrYXdxdnZjZ2F6cnRxdnN0eXlyIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc5MDc4NjE0NSwiZXhwIjoyMTA2MzYyMTQ1fQ.pzbpggNGOMJKG_fmIVRfa0rRjLVOk2pdnE2WtNQPT98"
        },
        {
          "key": "SUPABASE_BUCKET",
          "value": "hostel-room-images"
        }
      ]
    }
  ]
}
